#!/bin/bash

gcc -dumpspecs | sed -e 's@/dnatools@@g'                   \
    -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}' \
    -e '/\*cpp:/{n;s@$@ -I/usr/include@}' >      \
    `dirname $(gcc --print-libgcc-file-name)`/specs

