#!/bin/bash

grep fcron /etc/group || groupadd -g 22 fcron &&
grep fcron /etc/passwd || useradd -d /dev/null -c "Fcron User" -g fcron -s /bin/false -u 22 fcron

grep ^cron /etc/syslog.conf || cat >> /etc/syslog.conf << "EOF"
cron.* -/var/log/cron.log
EOF

/etc/init.d/syslogd reload

install -vdm754 /etc/cron.{hourly,daily,weekly,monthly}

cat > /var/spool/fcron/systab.orig << "EOF"
&bootrun 01 * * * * root run-parts /etc/cron.hourly
&bootrun 02 4 * * * root run-parts /etc/cron.daily
&bootrun 22 4 * * 0 root run-parts /etc/cron.weekly
&bootrun 42 4 1 * * root run-parts /etc/cron.monthly
EOF

fcrontab -z -u systab

