#!/bin/bash

grep "^named:" /etc/group || groupadd -g 41 named
grep "^named:" /etc/passwd || useradd -c "Named User" \
  -g named -s /bin/false \
  -d /etc/bind -u 41 named

chmod +x /etc/init.d/named

rc-update add named default

if [ ! -f '/etc/bind/rndc.key' ]; then
	if [ -f "/dev/urandom" ]; then
		# echo "Using /dev/urandom for generating rndc.key"
		/usr/sbin/rndc-confgen -r /dev/urandom -a
		# echo
	else
		# echo "Using /dev/random for generating rndc.key"
		/usr/sbin/rndc-confgen -a
		# echo
	fi
	chown named:named /etc/bind
	mv /etc/rndc.key /etc/bind/rndc.key
	chown root:named /etc/bind/rndc.key
	chmod 0640 /etc/bind/rndc.key
fi
