#!/bin/bash

grep "^lp:" /etc/passwd || useradd -c "Print Service User" -d /var/spool/cups -g lp -s /bin/false -u 9 lp
grep "^lpadmin:" /etc/group || groupadd -g 49 lpadmin && usermod -a -G lpadmin root

echo "ServerName /run/cups/cups.sock" > /etc/cups/client.conf

gtk-update-icon-cache -qtf /usr/share/icons/hicolor

rc-update add cupsd default
