#!/bin/bash

# clean files
rm -f /usr/share/dbus-1/services/keep
rm -f k/etc/dbus-1/session/keep
rm -f /etc/dbus-1/system.d/keep
rm -f /var/lib/dbus/keep

# configure dbus
dbus-uuidgen --ensure=/etc/machine-id
ln -sf /etc/machine-id /var/lib/dbus/machine-id

rc-update add dbus default
