#!/bin/bash

/usr/sbin/make-ca -g

install -vdm755 /etc/ssl/local

install -vdm755 /etc/cron.weekly
cat > /etc/cron.weekly/update-pki.sh << "EOF" &&
#!/bin/bash
/usr/sbin/make-ca -g
EOF

chmod 754 /etc/cron.weekly/update-pki.sh

ln -sfv /etc/pki/tls/certs/ca-bundle.crt \
        /etc/ssl/ca-bundle.crt

cd /etc/ssl/local

wget http://www.cacert.org/certs/root.crt
wget http://www.cacert.org/certs/class3.crt

openssl x509 -in root.crt -text -fingerprint -setalias "CAcert Class 1 root" \
        -addtrust serverAuth -addtrust emailProtection -addtrust codeSigning \
        > /etc/ssl/local/CAcert_Class_1_root.pem &&
openssl x509 -in class3.crt -text -fingerprint -setalias "CAcert Class 3 root" \
        -addtrust serverAuth -addtrust emailProtection -addtrust codeSigning \
        > /etc/ssl/local/CAcert_Class_3_root.pem

/usr/sbin/make-ca -r -f


