#!/bin/bash

/usr/sbin/make-ca -g

ln -sfv /etc/pki/tls/certs/ca-bundle.crt \
        /etc/ssl/ca-bundle.crt

cd /etc/ssl/local

openssl x509 -in root.crt -text -fingerprint -setalias "CAcert Class 1 root" \
        -addtrust serverAuth -addtrust emailProtection -addtrust codeSigning \
        > /etc/ssl/local/CAcert_Class_1_root.pem &&
openssl x509 -in class3.crt -text -fingerprint -setalias "CAcert Class 3 root" \
        -addtrust serverAuth -addtrust emailProtection -addtrust codeSigning \
        > /etc/ssl/local/CAcert_Class_3_root.pem

