#!/bin/bash

grep -i powerline /root/.bashrc || echo "# Uncomment to activate powerline!!!
# You must copy config files to .config/powerline!!!

#if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then
#	powerline-daemon -q
#	POWERLINE_BASH_CONTINUATION=1
#	POWERLINE_BASH_SELECT=1
#	source /usr/share/powerline/bindings/bash/powerline.sh
#fi
" >> /root/.bashrc

for f in /home/*/.bashrc; do
	grep -i powerline $f || echo "# Uncomment to activate powerline!!!
# You must copy config files to .config/powerline!!!

#if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then
#       powerline-daemon -q
#       POWERLINE_BASH_CONTINUATION=1
#       POWERLINE_BASH_SELECT=1
#       source /usr/share/powerline/bindings/bash/powerline.sh
#fi
" >> $f
done

grep powerline /etc/vimrc || \
echo '
let g:powerline_pycmd="py3"

set rtp+=/usr/lib/python3.7/site-packages/powerline/bindings/vim

" Always show statusline
set laststatus=2

" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256
' >> /etc/vimrc

