#!/bin/bash

groupadd -fg 84 avahi
useradd -c "Avahi Daemon Owner" -d /var/run/avahi-daemon -u 84 \
	-g avahi -s /bin/false avahi

groupadd -fg 86 netdev

rc-update add autoipd default
rc-update add avahi-daemon default
rc-update add avahi-dnsconfd default
