#!/bin/bash

chmod 644 /etc/pam.d/sshd &&
install -v -m700 -d /var/lib/sshd &&
chown -v root:sys /var/lib/sshd

grep "^sshd:" /etc/group || groupadd -g 50 sshd
grep "^sshd:" /etc/passwd || useradd  -c 'sshd PrivSep' \
         -d /var/lib/sshd  \
         -g sshd           \
         -s /bin/false     \
         -u 50 sshd

grep "^PermitRootLogin" /etc/ssh/sshd_config || echo "PermitRootLogin no" >> /etc/ssh/sshd_config
grep "^UsePAM" /etc/ssh/sshd_config || echo "UsePAM yes" >> /etc/ssh/sshd_config

for dev in $(ls /etc/init.d/net.* | grep -v "net.lo" | awk -F. '{print $NF}'); do
	if [ ! -f "/etc/init.d/sshd.$dev" ]; then
		ln -s sshd /etc/init.d/sshd.$dev
	fi;
	if [ ! -f "/etc/conf.d/sshd.$dev" ]; then
		cp /etc/conf.d/sshd /etc/conf.d/sshd.$dev
		echo 'rc_need="!net net.'$dev'"' >> /etc/conf.d/sshd.$dev
	fi;
	rc-update add sshd.$dev default
done
